# Generated by Django 5.0.7 on 2024-08-26 19:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1cbb89db-0259-4ce6-a163-2913a3ab3075'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
