# Generated by Django 5.0.7 on 2024-09-21 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_user_id_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f2c92f2-d7e4-46dc-b26f-76d817678231'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
