# Generated by Django 5.0.7 on 2024-09-21 16:09

import apps.user_auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user_auth.models.profile_image_upload_location, verbose_name='user media uploads'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca704ac9-1fe7-469b-ab86-620e3a858949'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
