# Generated by Django 5.0.7 on 2024-09-21 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_remove_user_profile_user_bio_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f91d792-1598-4a0e-92f6-1dd6bee97cb1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
