# Generated by Django 5.0.7 on 2024-09-29 14:43

import apps.user_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_agent_user_polymorphic_ctype_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agent',
            managers=[
                ('objects', apps.user_auth.models.AppUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user_auth.models.AppUserManager()),
            ],
        ),
    ]
