# Generated by Django 5.0.7 on 2024-10-07 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_stages'),
    ]

    operations = [

    ]
