# Generated by Django 5.0.7 on 2024-10-07 13:47

import apps.user_auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_user_signup_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(blank=True, help_text='Physical address of the vendor.', null=True, verbose_name='Address')),
                ('website', models.URLField(blank=True, help_text='Website of the vendor.', null=True, verbose_name='Website')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this vendor record was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'permissions': [],
            },
            bases=('user_auth.user',),
            managers=[
                ('objects', apps.user_auth.models.AppUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VendorOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.user_auth.models.product_image_upload_location)),
                ('offering_type', models.CharField(choices=[('SERV', 'Service'), ('PROD', 'Product')], max_length=10)),
                ('description', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per', models.CharField(max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='user_auth.vendor')),
            ],
        ),
    ]
