# Generated by Django 5.0.7 on 2024-10-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_alter_user_username'),
    ]

    operations = [

    ]
