# Generated by Django 5.0.7 on 2024-12-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_notification_created_at_notification_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
    ]
