# Generated by Django 5.0.7 on 2025-01-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0017_remove_user_bio_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='vendor',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
