# Generated by Django 5.0.7 on 2025-01-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0018_alter_agent_managers_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoroffering',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='user_auth.vendor'),
        ),
    ]
