# Generated by Django 5.0.7 on 2024-08-26 19:59

import apps.enterprise.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('description', models.TextField(verbose_name='Department description')),
                ('number_of_employee', models.IntegerField(verbose_name='Number of employees')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'permissions': [('can_add_employee', 'Can add employee'), ('can_remove_employee', 'Can remove employee'), ('can_view_budget', 'Can view budget'), ('can_edit_description', 'Can edit budget')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('01a30302-f6c4-4d24-8988-1c536a033de5'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name of organization/business/organisation')),
                ('email', models.EmailField(max_length=254, verbose_name='organization Email')),
                ('tel_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='organization Tel number')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Official operational address')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.enterprise.models.profile_image_upload_location, verbose_name='organization brand logo')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='organization description')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'permissions': [('can_add_admin_to_organization', 'Can add admin'), ('can_add_employee_to_organization', 'can and employee to organization'), ('can_add_department_to_organization', 'can add department to organization'), ('can_add_vendor_to_organization', 'Can add vendor to organization'), ('can_view_admin_to_organization', 'Can view admin'), ('can_view_employees_to_organization', 'Can view employees'), ('can_view_departments_to_organization', 'Can view departments'), ('can_view_vendors_to_organization', 'Can view vendors'), ('can_edit_vendor_to_organization', 'Can edit vendor'), ('can_delete_vendor_to_organization', 'Can delete vendor'), ('can_make_payment_request_to_organization', 'can and payment request to organization')],
            },
        ),
        migrations.CreateModel(
            name='EmploymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('employment_type', models.CharField(help_text='The employment type. E.g full-time worker or part-time worker', max_length=100, verbose_name='Employment Type')),
                ('is_active', models.BooleanField(default=True, help_text='Currently actively employed or on paid leave', verbose_name='Active Status')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('work_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Location')),
                ('work_hours', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work Hours')),
                ('contract_type', models.CharField(help_text='To specify the type of contract (e.g., permanent, temporary, freelance).', max_length=100, verbose_name='Contract Type')),
                ('performance_review_date', models.DateField(blank=True, help_text=' Date of the last performance review', null=True, verbose_name='Performance Review Date')),
                ('notes', models.TextField(blank=True, help_text="Additional notes or comments about the employee's employment.", null=True, verbose_name='Notes')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='enterprise.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(help_text='organisation this department belong', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='enterprise.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('contract_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='enterprise.employmentdetail')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='enterprise.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employed_at', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employmentdetail',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text="A reference to the employee's supervisor or manager.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_employees', to='enterprise.organizationemployee'),
        ),
        migrations.CreateModel(
            name='DepartmentHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.department')),
                ('organization_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.organizationemployee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hods',
            field=models.ManyToManyField(help_text='Head of department', related_name='hod_of', through='enterprise.DepartmentHOD', to='enterprise.organizationemployee'),
        ),
        migrations.CreateModel(
            name='OrganizationVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('offering_type', models.CharField(max_length=20, verbose_name='Offering of offering')),
                ('last_offering', models.DateField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(help_text='The organization this vendor supplies to.', on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='enterprise.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
