# Generated by Django 5.0.7 on 2024-09-29 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationemployee',
            name='contract_detail',
        ),
        migrations.RemoveField(
            model_name='organizationemployee',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationemployee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organizationvendor',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='organizationvendor',
            name='organization',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('AD', 'admin permission'), ('can_UD', 'can update and delete')], 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='number_of_employee',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.AddField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry_type',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FIN', 'Finance'), ('HEALTH', 'Healthcare'), ('EDU', 'Education'), ('RETAIL', 'Retail'), ('MANUF', 'Manufacturing'), ('AGRI', 'Agriculture'), ('CONS', 'Construction'), ('ENERGY', 'Energy'), ('TRANSP', 'Transportation'), ('MEDIA', 'Media'), ('HOSP', 'Hospitality'), ('REAL', 'Real Estate'), ('LEGAL', 'Legal Services'), ('GOV', 'Government'), ('NONPROFIT', 'Nonprofit')], default='blah', max_length=30, verbose_name='type of organization/business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(default='name', max_length=100, unique=True, verbose_name='name of organization/business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('CORP', 'Corporation'), ('LLC', 'Limited Liability Company'), ('NONPROFIT', 'Nonprofit Organization'), ('SOLE', 'Sole Proprietorship'), ('PARTNERSHIP', 'Partnership'), ('GOV', 'Government Agency'), ('EDU', 'Educational Institution'), ('COOP', 'Cooperative'), ('TRUST', 'Trust'), ('JV', 'Joint Venture')], default='type', max_length=15, verbose_name='type of organization/business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='AssociatetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('associate_type', models.CharField(help_text='The employment type. E.g vendor or worker', max_length=100, verbose_name='Employment Type')),
                ('is_active', models.BooleanField(default=True, help_text='Currently actively employed or on paid leave', verbose_name='Active Status')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
                ('work_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Location')),
                ('contract_type', models.CharField(help_text='To specify the type of contract (e.g., permanent, temporary, freelance).', max_length=100, verbose_name='Contract Type')),
                ('notes', models.TextField(blank=True, help_text="Additional notes or comments about the agent's employment.", null=True, verbose_name='Notes')),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='members', to='enterprise.department')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAssociateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('request_status', models.CharField(choices=[('PEND', 'Pending'), ('APPR', 'Approved'), ('REJT', 'Rejected')], max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate_request', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this vendor supplies to.', on_delete=django.db.models.deletion.CASCADE, related_name='_requests', to='enterprise.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAssociates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employed_at', to=settings.AUTH_USER_MODEL)),
                ('contract_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='enterprise.associatetdetail')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='enterprise.organization')),
            ],
            options={
                'unique_together': {('organization', 'associate')},
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='associates',
            field=models.ManyToManyField(related_name='organization', through='enterprise.OrganizationAssociates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='hods',
            field=models.ManyToManyField(help_text='Head of department', related_name='hod_of', through='enterprise.DepartmentHOD', to='enterprise.organizationassociates'),
        ),
        migrations.AlterField(
            model_name='departmenthod',
            name='organization_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.organizationassociates'),
        ),
        migrations.AlterUniqueTogether(
            name='departmenthod',
            unique_together={('department', 'organization_employee')},
        ),
        migrations.DeleteModel(
            name='EmploymentDetail',
        ),
        migrations.DeleteModel(
            name='OrganizationVendor',
        ),
        migrations.DeleteModel(
            name='OrganizationEmployee',
        ),
    ]
