# Generated by Django 5.0.7 on 2024-08-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationemployee',
            unique_together={('organization', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='departmenthod',
            unique_together={('department', 'organization_employee')},
        ),
    ]
