# Generated by Django 5.0.7 on 2024-09-30 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_remove_organizationemployee_contract_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationassociates',
            name='contract_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='enterprise.associatetdetail'),
        ),
    ]
