# Generated by Django 5.0.7 on 2024-10-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_alter_organizationassociates_contract_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationassociates',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associates_nl', to='enterprise.organization'),
        ),
    ]
