# Generated by Django 5.0.7 on 2024-10-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_alter_organizationassociates_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationassociates',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_associates', to='enterprise.organization'),
        ),
    ]
