# Generated by Django 5.0.7 on 2024-10-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_alter_organizationassociates_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssociatetDetail',
            new_name='AssociateDetail',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='associates',
        ),
    ]
