# Generated by Django 5.0.7 on 2024-10-06 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_rename_associatetdetail_associatedetail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='associates',
            field=models.ManyToManyField(related_name='organization', through='enterprise.OrganizationAssociates', to=settings.AUTH_USER_MODEL),
        ),
    ]
