# Generated by Django 5.0.7 on 2024-10-19 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_organization_associates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='associates',
            field=models.ManyToManyField(related_name='org_at', through='enterprise.OrganizationAssociates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationassociates',
            name='associate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
