# Generated by Django 5.0.7 on 2024-10-20 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_alter_organization_associates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationassociaterequest',
            constraint=models.UniqueConstraint(fields=('organization', 'associate'), name='unique_organization_associate'),
        ),
    ]
