# Generated by Django 5.0.7 on 2024-10-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0009_organizationassociaterequest_unique_organization_associate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associatedetail',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='associatedetail',
            name='associate_type',
        ),
        migrations.RemoveField(
            model_name='associatedetail',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='associatedetail',
            name='work_location',
        ),
    ]
