# Generated by Django 5.0.7 on 2024-10-21 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0010_rename_notes_associatedetail_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationassociaterequest',
            name='unique_organization_associate',
        ),
        migrations.AlterUniqueTogether(
            name='organizationassociates',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='associatedetail',
            name='end_date',
        ),
        migrations.AddField(
            model_name='associatedetail',
            name='associate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract_detail', to='enterprise.organizationassociates'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='organizationassociaterequest',
            constraint=models.UniqueConstraint(fields=('organization', 'associate'), name='unique_OrganizationAssociateRequest_organization_associate'),
        ),
        migrations.AddConstraint(
            model_name='organizationassociates',
            constraint=models.UniqueConstraint(fields=('organization', 'associate'), name='unique_OrganizationAssociates_organization_associate'),
        ),
        migrations.RemoveField(
            model_name='organizationassociates',
            name='contract_detail',
        ),
    ]
