# Generated by Django 5.0.7 on 2024-11-25 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_remove_organizationassociaterequest_unique_organization_associate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hods',
        ),
        migrations.DeleteModel(
            name='DepartmentHOD',
        ),
        migrations.AddField(
            model_name='department',
            name='hods',
            field=models.ForeignKey(default=0, help_text='Head of department', on_delete=django.db.models.deletion.PROTECT, related_name='hod_of', to='enterprise.organizationassociates'),
            preserve_default=False,
        ),
    ]
