# Generated by Django 5.0.7 on 2024-11-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_remove_department_hods_delete_departmenthod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='hods',
            new_name='hod',
        ),
    ]
