# Generated by Django 5.0.7 on 2024-11-26 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0013_rename_hods_department_hod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(help_text='Head of department', on_delete=django.db.models.deletion.PROTECT, related_name='hod_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
