# Generated by Django 5.0.7 on 2024-12-10 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0016_remove_associatedetail_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_Department_organization_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.AlterField(
            model_name='associatedetail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='associatedetail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='departent',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hod_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='enterprise.organization'),
        ),
        migrations.AddConstraint(
            model_name='departent',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_Department_organization_name'),
        ),
    ]
