# Generated by Django 5.0.7 on 2024-12-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0018_category_delete_departent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
