# Generated by Django 5.0.7 on 2024-12-10 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0019_delete_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hod',
        ),
        migrations.AddField(
            model_name='category',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_of', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
